name: dse_physics_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.1+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fl_chart: ^0.41.0
  provider: ^6.0.0
  flutter_math_fork: ^0.6.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.2.2
  google_fonts: ^2.1.0
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.0.0+2
  font_awesome_flutter: ^9.2.0
  google_mobile_ads: ^1.0.1
  favorite_button: ^0.0.4
#  for local storage
  hive: ^2.0.5
  hive_flutter: ^1.1.0
#  for firebase
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
#  for sign in
  google_sign_in: ^5.2.1
  flutter_signin_button: ^2.0.0
  flutter_facebook_auth: ^4.0.0
  sign_in_with_apple: ^3.3.0
#  for forced update app
  package_info_plus: ^1.3.0
  firebase_remote_config: ^1.0.4
  upgrader: ^3.12.1
# for loading animation
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  url_launcher: ^6.0.18
  introduction_screen: ^2.1.0
  flutter_local_notifications: ^9.2.0
  timezone: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
    # hive database generators
  build_runner: ^2.1.7
  hive_generator: ^1.1.1
  flutter_native_splash: ^1.3.3

flutter_native_splash:
  color: "#ffffff"
  image: images/launch_700.png
  android: true
  ios: true

flutter:


  uses-material-design: true
  assets:
    - images/phyanywhere_logo.png
    - images/quiz_logo.png
    - images/revision_logo.png
    - images/intro_image01.png
    - images/intro_image02.png
    - images/intro_image03.png

